version: "3"
services:
  db:
    image: postgres:12
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres:/var/lib/postgresql/data
  # mqtt:
  #   image: 'hivemq/hivemq-ce:latest'
  #   ports:
  #     - ${MQTT_PORT}:1883
  #     - ${MQTT_WS_PORT}:8000
  #   healthcheck:
  #     test: ["CMD", "echo", "\"\"", ">", "/dev/tcp/127.0.0.1/1883"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  # mqtt:
  #   image: 'hivemq/hivemq4:latest'
  #   ports:
  #     - ${MQTT_PORT}:1883
  #     - ${MQTT_WS_PORT}:8000
  #     - ${MQTT_WEB_UI_PORT}:8080
  #   healthcheck:
  #     test: ["CMD", "echo", "\"\"", ">", "/dev/tcp/127.0.0.1/1883"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  # mqtt:
  #   image: 'eclipse-mosquitto:1.6'
  #   ports:
  #     - ${MQTT_PORT}:1883
  #     - ${MQTT_WS_PORT}:8000
  #   environment:
  #     - MQTT_USER=${MQTT_USERNAME}
  #     - MQTT_PASSWORD=${MQTT_PASSWORD}
  #   healthcheck:
  #     test: ["CMD", "echo", "\"\"", ">", "/dev/tcp/127.0.0.1/1883"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10

  mqtt:
    image: emqx:5.4.0
    ports:
      - ${MQTT_PORT}:1883
      - ${MQTT_WS_PORT}:8083
      - ${MQTT_WEB_UI_PORT}:18083
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5

volumes:
  postgres: ~
